import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'es' | 'en' | 'ca' | 'fr' | 'de' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getLanguageName: (lang: Language) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': '¡Bienvenido! Tu estancia comienza aquí ✨',
    'welcome.guestsRegistered': 'Huéspedes registrados',
    'welcome.completeRegistration': 'Completar mi registro',
    'welcome.step': 'Paso 1 de 3',
    'welcome.share': 'Compartir enlace',
    'welcome.viewAccommodation': 'Ver alojamiento',
    'welcome.dataProtected': '🔒 Tus datos están protegidos y encriptados',
    'welcome.compliance': 'Cumplimos con el RGPD y normativa española de hospedaje',
    'welcome.timeEstimate': '📋 Completa tu registro en solo 3 minutos',
    'welcome.contact': 'Contactar',
    'dashboard.myStay': 'Mi Estancia',
    'dashboard.myReservation': 'Mi Reserva',
    'dashboard.openAccommodation': '🔓 Abrir Alojamiento',
    'dashboard.preferences': 'Preferencias de Estancia',
    'dashboard.yourHost': 'Tu Anfitrión',
    'dashboard.accommodationInfo': 'Información del Alojamiento',
    'dashboard.welcomeVideo': 'Video de Bienvenida',
    'dashboard.localGuide': 'Guía Local',
    'dashboard.customerSupport': 'Atención al Cliente',
    'dashboard.completeToUnlock': 'Completa tu registro para desbloquear',
    'dashboard.sendMessage': '💬 Enviar mensaje',
    'dashboard.callNow': '📞 Llamar ahora',
    'dashboard.sendEmail': '📧 Enviar email',
    'dashboard.missingGuests': 'Faltan huéspedes por registrar',
    'dashboard.someFeaturesLimited': 'Algunas funciones están limitadas hasta que todos los huéspedes se registren',
    'dashboard.reportIncident': 'Reportar incidencia',
    'dashboard.reportIncidentTitle': 'Reportar una Incidencia',
    'dashboard.incidentDescription': 'Describe el problema',
    'dashboard.incidentSubmit': 'Enviar reporte',
    'dashboard.incidentCancel': 'Cancelar',
    'dashboard.openDoor': 'Abrir Puerta Principal',
    'dashboard.openGarage': 'Abrir Garaje',
    'dashboard.unlockHistory': 'Historial de Aperturas',
    'dashboard.unlockSuccess': 'Puerta abierta exitosamente',
    'dashboard.unlockFailed': 'Error al abrir la puerta',
    'localGuide.restaurants': '🍽️ Restaurantes',
    'localGuide.cafes': '☕ Cafeterías',
    'localGuide.supermarkets': '🛒 Supermercados',
    'localGuide.transport': '🚇 Transporte público',
    'localGuide.tourist': '🏛️ Lugares turísticos',
    'localGuide.emergency': '🏥 Servicios de emergencia',
    'localGuide.entertainment': '🎭 Ocio y entretenimiento',
    'contact.title': 'Contactar Anfitrión',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Disponible 24/7 para emergencias',
    'share.title': 'Compartir Enlace de Registro',
    'share.message': 'Completa tu registro para Casa Vista Hermosa',
    'share.copy': 'Copiar enlace',
    'share.whatsapp': 'Compartir por WhatsApp',
    'share.email': 'Compartir por Email',
    'share.copied': '¡Enlace copiado!',
  },
  en: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': 'Welcome! Your stay begins here ✨',
    'welcome.guestsRegistered': 'Registered guests',
    'welcome.completeRegistration': 'Complete my registration',
    'welcome.step': 'Step 1 of 3',
    'welcome.share': 'Share link',
    'welcome.viewAccommodation': 'View accommodation',
    'welcome.dataProtected': '🔒 Your data is protected and encrypted',
    'welcome.compliance': 'We comply with GDPR and Spanish hosting regulations',
    'welcome.timeEstimate': '📋 Complete your registration in just 3 minutes',
    'welcome.contact': 'Contact',
    'dashboard.myStay': 'My Stay',
    'dashboard.myReservation': 'My Reservation',
    'dashboard.openAccommodation': '🔓 Open Accommodation',
    'dashboard.preferences': 'Stay Preferences',
    'dashboard.yourHost': 'Your Host',
    'dashboard.accommodationInfo': 'Accommodation Information',
    'dashboard.welcomeVideo': 'Welcome Video',
    'dashboard.localGuide': 'Local Guide',
    'dashboard.customerSupport': 'Customer Support',
    'dashboard.completeToUnlock': 'Complete your registration to unlock',
    'dashboard.sendMessage': '💬 Send message',
    'dashboard.callNow': '📞 Call now',
    'dashboard.sendEmail': '📧 Send email',
    'dashboard.missingGuests': 'Missing guests to register',
    'dashboard.someFeaturesLimited': 'Some features are limited until all guests register',
    'dashboard.reportIncident': 'Report incident',
    'dashboard.reportIncidentTitle': 'Report an Incident',
    'dashboard.incidentDescription': 'Describe the problem',
    'dashboard.incidentSubmit': 'Submit report',
    'dashboard.incidentCancel': 'Cancel',
    'dashboard.openDoor': 'Open Main Door',
    'dashboard.openGarage': 'Open Garage',
    'dashboard.unlockHistory': 'Unlock History',
    'dashboard.unlockSuccess': 'Door opened successfully',
    'dashboard.unlockFailed': 'Failed to open door',
    'localGuide.restaurants': '🍽️ Restaurants',
    'localGuide.cafes': '☕ Cafes',
    'localGuide.supermarkets': '🛒 Supermarkets',
    'localGuide.transport': '🚇 Public Transport',
    'localGuide.tourist': '🏛️ Tourist Attractions',
    'localGuide.emergency': '🏥 Emergency Services',
    'localGuide.entertainment': '🎭 Entertainment',
    'contact.title': 'Contact Host',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Available 24/7 for emergencies',
    'share.title': 'Share Registration Link',
    'share.message': 'Complete your registration for Casa Vista Hermosa',
    'share.copy': 'Copy link',
    'share.whatsapp': 'Share via WhatsApp',
    'share.email': 'Share via Email',
    'share.copied': 'Link copied!',
  },
  ca: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': 'Benvingut! La teva estada comença aquí ✨',
    'welcome.guestsRegistered': 'Hostes registrats',
    'welcome.completeRegistration': 'Completar el meu registre',
    'welcome.step': 'Pas 1 de 3',
    'welcome.share': 'Compartir enllaç',
    'welcome.viewAccommodation': 'Veure allotjament',
    'welcome.dataProtected': '🔒 Les teves dades estan protegides i encriptades',
    'welcome.compliance': 'Complim amb el RGPD i normativa espanyola d\'allotjament',
    'welcome.timeEstimate': '📋 Completa el teu registre en només 3 minuts',
    'welcome.contact': 'Contactar',
    'dashboard.myStay': 'La Meva Estada',
    'dashboard.myReservation': 'La Meva Reserva',
    'dashboard.openAccommodation': '🔓 Obrir Allotjament',
    'dashboard.preferences': 'Preferències d\'Estada',
    'dashboard.yourHost': 'El Teu Amfitrió',
    'dashboard.accommodationInfo': 'Informació de l\'Allotjament',
    'dashboard.welcomeVideo': 'Vídeo de Benvinguda',
    'dashboard.localGuide': 'Guia Local',
    'dashboard.customerSupport': 'Atenció al Client',
    'dashboard.completeToUnlock': 'Completa el teu registre per desbloquejar',
    'dashboard.sendMessage': '💬 Enviar missatge',
    'dashboard.callNow': '📞 Trucar ara',
    'dashboard.sendEmail': '📧 Enviar email',
    'localGuide.restaurants': '🍽️ Restaurants',
    'localGuide.cafes': '☕ Cafeteries',
    'localGuide.supermarkets': '🛒 Supermercats',
    'localGuide.transport': '🚇 Transport públic',
    'localGuide.tourist': '🏛️ Llocs turístics',
    'localGuide.emergency': '🏥 Serveis d\'emergència',
    'localGuide.entertainment': '🎭 Oci i entreteniment',
    'contact.title': 'Contactar Amfitrió',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Disponible 24/7 per emergències',
    'share.title': 'Compartir Enllaç de Registre',
    'share.message': 'Completa el teu registre per Casa Vista Hermosa',
    'share.copy': 'Copiar enllaç',
    'share.whatsapp': 'Compartir per WhatsApp',
    'share.email': 'Compartir per Email',
    'share.copied': 'Enllaç copiat!',
  },
  fr: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': 'Bienvenue! Votre séjour commence ici ✨',
    'welcome.guestsRegistered': 'Invités enregistrés',
    'welcome.completeRegistration': 'Compléter mon inscription',
    'welcome.step': 'Étape 1 sur 3',
    'welcome.share': 'Partager le lien',
    'welcome.viewAccommodation': 'Voir l\'hébergement',
    'welcome.dataProtected': '🔒 Vos données sont protégées et cryptées',
    'welcome.compliance': 'Nous respectons le RGPD et la réglementation espagnole',
    'welcome.timeEstimate': '📋 Complétez votre inscription en seulement 3 minutes',
    'welcome.contact': 'Contacter',
    'dashboard.myStay': 'Mon Séjour',
    'dashboard.myReservation': 'Ma Réservation',
    'dashboard.openAccommodation': '🔓 Ouvrir l\'Hébergement',
    'dashboard.preferences': 'Préférences de Séjour',
    'dashboard.yourHost': 'Votre Hôte',
    'dashboard.accommodationInfo': 'Informations sur l\'Hébergement',
    'dashboard.welcomeVideo': 'Vidéo de Bienvenue',
    'dashboard.localGuide': 'Guide Local',
    'dashboard.customerSupport': 'Service Client',
    'dashboard.completeToUnlock': 'Complétez votre inscription pour déverrouiller',
    'dashboard.sendMessage': '💬 Envoyer un message',
    'dashboard.callNow': '📞 Appeler maintenant',
    'dashboard.sendEmail': '📧 Envoyer un email',
    'localGuide.restaurants': '🍽️ Restaurants',
    'localGuide.cafes': '☕ Cafés',
    'localGuide.supermarkets': '🛒 Supermarchés',
    'localGuide.transport': '🚇 Transport public',
    'localGuide.tourist': '🏛️ Attractions touristiques',
    'localGuide.emergency': '🏥 Services d\'urgence',
    'localGuide.entertainment': '🎭 Divertissement',
    'contact.title': 'Contacter l\'Hôte',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Disponible 24h/24 pour les urgences',
    'share.title': 'Partager le Lien d\'Inscription',
    'share.message': 'Complétez votre inscription pour Casa Vista Hermosa',
    'share.copy': 'Copier le lien',
    'share.whatsapp': 'Partager via WhatsApp',
    'share.email': 'Partager par Email',
    'share.copied': 'Lien copié!',
  },
  de: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': 'Willkommen! Ihr Aufenthalt beginnt hier ✨',
    'welcome.guestsRegistered': 'Registrierte Gäste',
    'welcome.completeRegistration': 'Meine Registrierung abschließen',
    'welcome.step': 'Schritt 1 von 3',
    'welcome.share': 'Link teilen',
    'welcome.viewAccommodation': 'Unterkunft ansehen',
    'welcome.dataProtected': '🔒 Ihre Daten sind geschützt und verschlüsselt',
    'welcome.compliance': 'Wir erfüllen die DSGVO und spanische Vorschriften',
    'welcome.timeEstimate': '📋 Schließen Sie Ihre Registrierung in nur 3 Minuten ab',
    'welcome.contact': 'Kontakt',
    'dashboard.myStay': 'Mein Aufenthalt',
    'dashboard.myReservation': 'Meine Reservierung',
    'dashboard.openAccommodation': '🔓 Unterkunft öffnen',
    'dashboard.preferences': 'Aufenthaltspräferenzen',
    'dashboard.yourHost': 'Ihr Gastgeber',
    'dashboard.accommodationInfo': 'Unterkunftsinformationen',
    'dashboard.welcomeVideo': 'Willkommensvideo',
    'dashboard.localGuide': 'Lokaler Führer',
    'dashboard.customerSupport': 'Kundenservice',
    'dashboard.completeToUnlock': 'Schließen Sie Ihre Registrierung ab zum Entsperren',
    'dashboard.sendMessage': '💬 Nachricht senden',
    'dashboard.callNow': '📞 Jetzt anrufen',
    'dashboard.sendEmail': '📧 E-Mail senden',
    'localGuide.restaurants': '🍽️ Restaurants',
    'localGuide.cafes': '☕ Cafés',
    'localGuide.supermarkets': '🛒 Supermärkte',
    'localGuide.transport': '🚇 Öffentliche Verkehrsmittel',
    'localGuide.tourist': '🏛️ Touristische Attraktionen',
    'localGuide.emergency': '🏥 Notdienste',
    'localGuide.entertainment': '🎭 Unterhaltung',
    'contact.title': 'Gastgeber kontaktieren',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Verfügbar 24/7 für Notfälle',
    'share.title': 'Registrierungslink teilen',
    'share.message': 'Schließen Sie Ihre Registrierung für Casa Vista Hermosa ab',
    'share.copy': 'Link kopieren',
    'share.whatsapp': 'Über WhatsApp teilen',
    'share.email': 'Per E-Mail teilen',
    'share.copied': 'Link kopiert!',
  },
  nl: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': 'Welkom! Uw verblijf begint hier ✨',
    'welcome.guestsRegistered': 'Geregistreerde gasten',
    'welcome.completeRegistration': 'Mijn registratie voltooien',
    'welcome.step': 'Stap 1 van 3',
    'welcome.share': 'Link delen',
    'welcome.viewAccommodation': 'Accommodatie bekijken',
    'welcome.dataProtected': '🔒 Uw gegevens zijn beschermd en versleuteld',
    'welcome.compliance': 'We voldoen aan de AVG en Spaanse regelgeving',
    'welcome.timeEstimate': '📋 Voltooi uw registratie in slechts 3 minuten',
    'welcome.contact': 'Contact',
    'dashboard.myStay': 'Mijn Verblijf',
    'dashboard.myReservation': 'Mijn Reservering',
    'dashboard.openAccommodation': '🔓 Accommodatie openen',
    'dashboard.preferences': 'Verblijfsvoorkeuren',
    'dashboard.yourHost': 'Uw Gastheer',
    'dashboard.accommodationInfo': 'Accommodatie Informatie',
    'dashboard.welcomeVideo': 'Welkomstvideo',
    'dashboard.localGuide': 'Lokale Gids',
    'dashboard.customerSupport': 'Klantenservice',
    'dashboard.completeToUnlock': 'Voltooi uw registratie om te ontgrendelen',
    'dashboard.sendMessage': '💬 Bericht versturen',
    'dashboard.callNow': '📞 Nu bellen',
    'dashboard.sendEmail': '📧 E-mail versturen',
    'localGuide.restaurants': '🍽️ Restaurants',
    'localGuide.cafes': '☕ Cafés',
    'localGuide.supermarkets': '🛒 Supermarkten',
    'localGuide.transport': '🚇 Openbaar vervoer',
    'localGuide.tourist': '🏛️ Toeristische attracties',
    'localGuide.emergency': '🏥 Nooddiensten',
    'localGuide.entertainment': '🎭 Entertainment',
    'contact.title': 'Gastheer contacteren',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Beschikbaar 24/7 voor noodgevallen',
    'share.title': 'Registratielink delen',
    'share.message': 'Voltooi uw registratie voor Casa Vista Hermosa',
    'share.copy': 'Link kopiëren',
    'share.whatsapp': 'Delen via WhatsApp',
    'share.email': 'Delen via e-mail',
    'share.copied': 'Link gekopieerd!',
  },
};

const languageNames: Record<Language, string> = {
  es: 'Español',
  en: 'English',
  ca: 'Català',
  fr: 'Français',
  de: 'Deutsch',
  nl: 'Nederlands',
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const getLanguageName = (lang: Language): string => {
    return languageNames[lang];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getLanguageName }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
