import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'es' | 'en' | 'ca' | 'fr' | 'de' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getLanguageName: (lang: Language) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': '¡Bienvenido! Tu estancia comienza aquí ✨',
    'welcome.guestsRegistered': 'Huéspedes registrados',
    'welcome.completeRegistration': 'Completar mi registro',
    'welcome.step': 'Paso 1 de 3',
    'welcome.share': 'Compartir enlace',
    'welcome.viewAccommodation': 'Ver alojamiento',
    'welcome.dataProtected': '🔒 Tus datos están protegidos y encriptados',
    'welcome.compliance': 'Cumplimos con el RGPD y normativa española de hospedaje',
    'welcome.timeEstimate': '📋 Completa tu registro en solo 3 minutos',
    'welcome.contact': 'Contactar',
    'dashboard.myStay': 'Mi Estancia',
    'dashboard.myReservation': 'Mi Reserva',
    'dashboard.openAccommodation': '🔓 Abrir Alojamiento',
    'dashboard.preferences': 'Preferencias de Estancia',
    'dashboard.yourHost': 'Tu Anfitrión',
    'dashboard.accommodationInfo': 'Información del Alojamiento',
    'dashboard.welcomeVideo': 'Video de Bienvenida',
    'dashboard.localGuide': 'Guía Local',
    'dashboard.customerSupport': 'Atención al Cliente',
    'dashboard.completeToUnlock': 'Completa tu registro para desbloquear',
    'dashboard.sendMessage': '💬 Enviar mensaje',
    'dashboard.callNow': '📞 Llamar ahora',
    'dashboard.sendEmail': '📧 Enviar email',
    'dashboard.missingGuests': 'Faltan huéspedes por registrar',
    'dashboard.someFeaturesLimited': 'Algunas funciones están limitadas hasta que todos los huéspedes se registren',
    'dashboard.reportIncident': 'Reportar incidencia',
    'dashboard.reportIncidentTitle': 'Reportar una Incidencia',
    'dashboard.incidentDescription': 'Describe el problema',
    'dashboard.incidentSubmit': 'Enviar reporte',
    'dashboard.incidentCancel': 'Cancelar',
    'dashboard.openDoor': 'Abrir Puerta Principal',
    'dashboard.openGarage': 'Abrir Garaje',
    'dashboard.unlockHistory': 'Historial de Aperturas',
    'dashboard.unlockSuccess': 'Puerta abierta exitosamente',
    'dashboard.unlockFailed': 'Error al abrir la puerta',
    'localGuide.restaurants': '🍽️ Restaurantes',
    'localGuide.cafes': '☕ Cafeterías',
    'localGuide.supermarkets': '🛒 Supermercados',
    'localGuide.transport': '🚇 Transporte público',
    'localGuide.tourist': '🏛️ Lugares turísticos',
    'localGuide.emergency': '🏥 Servicios de emergencia',
    'localGuide.entertainment': '🎭 Ocio y entretenimiento',
    'contact.title': 'Contactar Anfitrión',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Disponible 24/7 para emergencias',
    'share.title': 'Compartir Enlace de Registro',
    'share.message': 'Completa tu registro para Casa Vista Hermosa',
    'share.copy': 'Copiar enlace',
    'share.whatsapp': 'Compartir por WhatsApp',
    'share.email': 'Compartir por Email',
    'share.copied': '¡Enlace copiado!',
    'confirmation.title': '¡Registro Completo!',
    'confirmation.thankYou': 'Gracias',
    'confirmation.dataSaved': 'Tu información ha sido guardada correctamente',
    'confirmation.groupStatus': 'Estado del Grupo',
    'confirmation.of': 'de',
    'confirmation.responsible': 'Responsable',
    'confirmation.registered': 'Registrado',
    'confirmation.pending': 'Pendiente',
    'confirmation.registerNext': 'Registrar siguiente huésped',
    'confirmation.pendingPlural': 'pendientes',
    'confirmation.pendingSingular': 'pendiente',
    'confirmation.allRegistered': '¡Todos los huéspedes han completado su registro!',
    'confirmation.allGuestsComplete': '¡Todos los huéspedes registrados!',
    'confirmation.fullAccessUnlocked': 'Acceso completo desbloqueado',
    'confirmation.goToDashboard': 'Ir a Mi Estancia',
    'confirmation.shareRegistration': 'Compartir Registro',
    'confirmation.shareDescription': 'Envía este enlace a los demás huéspedes para que completen su registro',
    'confirmation.copyLink': 'Copiar enlace de registro',
    'confirmation.shareWhatsApp': 'Compartir por WhatsApp',
    'confirmation.shareEmail': 'Enviar por Email',
    'confirmation.showQR': 'Mostrar código QR',
    'confirmation.continueToApp': 'Continuar a la app',
    'confirmation.limitedFeatures': 'Algunas funciones estarán limitadas hasta que todos los huéspedes completen su registro',
    'confirmation.progressSaved': 'Tu progreso se ha guardado correctamente',
  },
  en: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': 'Welcome! Your stay begins here ✨',
    'welcome.guestsRegistered': 'Registered guests',
    'welcome.completeRegistration': 'Complete my registration',
    'welcome.step': 'Step 1 of 3',
    'welcome.share': 'Share link',
    'welcome.viewAccommodation': 'View accommodation',
    'welcome.dataProtected': '🔒 Your data is protected and encrypted',
    'welcome.compliance': 'We comply with GDPR and Spanish hosting regulations',
    'welcome.timeEstimate': '📋 Complete your registration in just 3 minutes',
    'welcome.contact': 'Contact',
    'dashboard.myStay': 'My Stay',
    'dashboard.myReservation': 'My Reservation',
    'dashboard.openAccommodation': '🔓 Open Accommodation',
    'dashboard.preferences': 'Stay Preferences',
    'dashboard.yourHost': 'Your Host',
    'dashboard.accommodationInfo': 'Accommodation Information',
    'dashboard.welcomeVideo': 'Welcome Video',
    'dashboard.localGuide': 'Local Guide',
    'dashboard.customerSupport': 'Customer Support',
    'dashboard.completeToUnlock': 'Complete your registration to unlock',
    'dashboard.sendMessage': '💬 Send message',
    'dashboard.callNow': '📞 Call now',
    'dashboard.sendEmail': '📧 Send email',
    'dashboard.missingGuests': 'Missing guests to register',
    'dashboard.someFeaturesLimited': 'Some features are limited until all guests register',
    'dashboard.reportIncident': 'Report incident',
    'dashboard.reportIncidentTitle': 'Report an Incident',
    'dashboard.incidentDescription': 'Describe the problem',
    'dashboard.incidentSubmit': 'Submit report',
    'dashboard.incidentCancel': 'Cancel',
    'dashboard.openDoor': 'Open Main Door',
    'dashboard.openGarage': 'Open Garage',
    'dashboard.unlockHistory': 'Unlock History',
    'dashboard.unlockSuccess': 'Door opened successfully',
    'dashboard.unlockFailed': 'Failed to open door',
    'localGuide.restaurants': '🍽️ Restaurants',
    'localGuide.cafes': '☕ Cafes',
    'localGuide.supermarkets': '🛒 Supermarkets',
    'localGuide.transport': '🚇 Public Transport',
    'localGuide.tourist': '🏛️ Tourist Attractions',
    'localGuide.emergency': '🏥 Emergency Services',
    'localGuide.entertainment': '🎭 Entertainment',
    'contact.title': 'Contact Host',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Available 24/7 for emergencies',
    'share.title': 'Share Registration Link',
    'share.message': 'Complete your registration for Casa Vista Hermosa',
    'share.copy': 'Copy link',
    'share.whatsapp': 'Share via WhatsApp',
    'share.email': 'Share via Email',
    'share.copied': 'Link copied!',
    'confirmation.title': 'Registration Complete!',
    'confirmation.thankYou': 'Thank you',
    'confirmation.dataSaved': 'Your information has been saved correctly',
    'confirmation.groupStatus': 'Group Status',
    'confirmation.of': 'of',
    'confirmation.responsible': 'Responsible',
    'confirmation.registered': 'Registered',
    'confirmation.pending': 'Pending',
    'confirmation.registerNext': 'Register next guest',
    'confirmation.pendingPlural': 'pending',
    'confirmation.pendingSingular': 'pending',
    'confirmation.allRegistered': 'All guests have completed their registration!',
    'confirmation.allGuestsComplete': 'All guests registered!',
    'confirmation.fullAccessUnlocked': 'Full access unlocked',
    'confirmation.goToDashboard': 'Go to My Stay',
    'confirmation.shareRegistration': 'Share Registration',
    'confirmation.shareDescription': 'Send this link to other guests so they can complete their registration',
    'confirmation.copyLink': 'Copy registration link',
    'confirmation.shareWhatsApp': 'Share via WhatsApp',
    'confirmation.shareEmail': 'Send via Email',
    'confirmation.showQR': 'Show QR code',
    'confirmation.continueToApp': 'Continue to app',
    'confirmation.limitedFeatures': 'Some features will be limited until all guests complete their registration',
    'confirmation.progressSaved': 'Your progress has been saved correctly',
  },
  ca: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': 'Benvingut! La teva estada comença aquí ✨',
    'welcome.guestsRegistered': 'Hostes registrats',
    'welcome.completeRegistration': 'Completar el meu registre',
    'welcome.step': 'Pas 1 de 3',
    'welcome.share': 'Compartir enllaç',
    'welcome.viewAccommodation': 'Veure allotjament',
    'welcome.dataProtected': '🔒 Les teves dades estan protegides i encriptades',
    'welcome.compliance': 'Complim amb el RGPD i normativa espanyola d\'allotjament',
    'welcome.timeEstimate': '📋 Completa el teu registre en només 3 minuts',
    'welcome.contact': 'Contactar',
    'dashboard.myStay': 'La Meva Estada',
    'dashboard.myReservation': 'La Meva Reserva',
    'dashboard.openAccommodation': '🔓 Obrir Allotjament',
    'dashboard.preferences': 'Preferències d\'Estada',
    'dashboard.yourHost': 'El Teu Amfitrió',
    'dashboard.accommodationInfo': 'Informació de l\'Allotjament',
    'dashboard.welcomeVideo': 'Vídeo de Benvinguda',
    'dashboard.localGuide': 'Guia Local',
    'dashboard.customerSupport': 'Atenció al Client',
    'dashboard.completeToUnlock': 'Completa el teu registre per desbloquejar',
    'dashboard.sendMessage': '💬 Enviar missatge',
    'dashboard.callNow': '📞 Trucar ara',
    'dashboard.sendEmail': '📧 Enviar email',
    'dashboard.missingGuests': 'Falten hostes per registrar',
    'dashboard.someFeaturesLimited': 'Algunes funcions estan limitades fins que tots els hostes es registrin',
    'dashboard.reportIncident': 'Reportar incidència',
    'dashboard.reportIncidentTitle': 'Reportar una Incidència',
    'dashboard.incidentDescription': 'Descriu el problema',
    'dashboard.incidentSubmit': 'Enviar informe',
    'dashboard.incidentCancel': 'Cancel·lar',
    'dashboard.openDoor': 'Obrir Porta Principal',
    'dashboard.openGarage': 'Obrir Garatge',
    'dashboard.unlockHistory': 'Historial d\'Obertures',
    'dashboard.unlockSuccess': 'Porta oberta amb èxit',
    'dashboard.unlockFailed': 'Error en obrir la porta',
    'localGuide.restaurants': '🍽️ Restaurants',
    'localGuide.cafes': '☕ Cafeteries',
    'localGuide.supermarkets': '🛒 Supermercats',
    'localGuide.transport': '🚇 Transport públic',
    'localGuide.tourist': '🏛️ Llocs turístics',
    'localGuide.emergency': '🏥 Serveis d\'emergència',
    'localGuide.entertainment': '🎭 Oci i entreteniment',
    'contact.title': 'Contactar Amfitrió',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Disponible 24/7 per emergències',
    'share.title': 'Compartir Enllaç de Registre',
    'share.message': 'Completa el teu registre per Casa Vista Hermosa',
    'share.copy': 'Copiar enllaç',
    'share.whatsapp': 'Compartir per WhatsApp',
    'share.email': 'Compartir per Email',
    'share.copied': 'Enllaç copiat!',
    'confirmation.title': 'Registre Complet!',
    'confirmation.thankYou': 'Gràcies',
    'confirmation.dataSaved': 'La teva informació s\'ha guardat correctament',
    'confirmation.groupStatus': 'Estat del Grup',
    'confirmation.of': 'de',
    'confirmation.responsible': 'Responsable',
    'confirmation.registered': 'Registrat',
    'confirmation.pending': 'Pendent',
    'confirmation.registerNext': 'Registrar següent hoste',
    'confirmation.pendingPlural': 'pendents',
    'confirmation.pendingSingular': 'pendent',
    'confirmation.allRegistered': 'Tots els hostes han completat el seu registre!',
    'confirmation.allGuestsComplete': 'Tots els hostes registrats!',
    'confirmation.fullAccessUnlocked': 'Accés complet desbloquejat',
    'confirmation.goToDashboard': 'Anar a La Meva Estada',
    'confirmation.shareRegistration': 'Compartir Registre',
    'confirmation.shareDescription': 'Envia aquest enllaç als altres hostes perquè completin el seu registre',
    'confirmation.copyLink': 'Copiar enllaç de registre',
    'confirmation.shareWhatsApp': 'Compartir per WhatsApp',
    'confirmation.shareEmail': 'Enviar per Email',
    'confirmation.showQR': 'Mostrar codi QR',
    'confirmation.continueToApp': 'Continuar a l\'app',
    'confirmation.limitedFeatures': 'Algunes funcions estaran limitades fins que tots els hostes completin el seu registre',
    'confirmation.progressSaved': 'El teu progrés s\'ha guardat correctament',
  },
  fr: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': 'Bienvenue! Votre séjour commence ici ✨',
    'welcome.guestsRegistered': 'Invités enregistrés',
    'welcome.completeRegistration': 'Compléter mon inscription',
    'welcome.step': 'Étape 1 sur 3',
    'welcome.share': 'Partager le lien',
    'welcome.viewAccommodation': 'Voir l\'hébergement',
    'welcome.dataProtected': '🔒 Vos données sont protégées et cryptées',
    'welcome.compliance': 'Nous respectons le RGPD et la réglementation espagnole',
    'welcome.timeEstimate': '📋 Complétez votre inscription en seulement 3 minutes',
    'welcome.contact': 'Contacter',
    'dashboard.myStay': 'Mon Séjour',
    'dashboard.myReservation': 'Ma Réservation',
    'dashboard.openAccommodation': '🔓 Ouvrir l\'Hébergement',
    'dashboard.preferences': 'Préférences de Séjour',
    'dashboard.yourHost': 'Votre Hôte',
    'dashboard.accommodationInfo': 'Informations sur l\'Hébergement',
    'dashboard.welcomeVideo': 'Vidéo de Bienvenue',
    'dashboard.localGuide': 'Guide Local',
    'dashboard.customerSupport': 'Service Client',
    'dashboard.completeToUnlock': 'Complétez votre inscription pour déverrouiller',
    'dashboard.sendMessage': '💬 Envoyer un message',
    'dashboard.callNow': '📞 Appeler maintenant',
    'dashboard.sendEmail': '📧 Envoyer un email',
    'dashboard.missingGuests': 'Invités manquants à enregistrer',
    'dashboard.someFeaturesLimited': 'Certaines fonctionnalités sont limitées jusqu\'à ce que tous les invités s\'enregistrent',
    'dashboard.reportIncident': 'Signaler un incident',
    'dashboard.reportIncidentTitle': 'Signaler un Incident',
    'dashboard.incidentDescription': 'Décrivez le problème',
    'dashboard.incidentSubmit': 'Envoyer le rapport',
    'dashboard.incidentCancel': 'Annuler',
    'dashboard.openDoor': 'Ouvrir la Porte Principale',
    'dashboard.openGarage': 'Ouvrir le Garage',
    'dashboard.unlockHistory': 'Historique des Ouvertures',
    'dashboard.unlockSuccess': 'Porte ouverte avec succès',
    'dashboard.unlockFailed': 'Échec de l\'ouverture de la porte',
    'localGuide.restaurants': '🍽️ Restaurants',
    'localGuide.cafes': '☕ Cafés',
    'localGuide.supermarkets': '🛒 Supermarchés',
    'localGuide.transport': '🚇 Transport public',
    'localGuide.tourist': '🏛️ Attractions touristiques',
    'localGuide.emergency': '🏥 Services d\'urgence',
    'localGuide.entertainment': '🎭 Divertissement',
    'contact.title': 'Contacter l\'Hôte',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Disponible 24h/24 pour les urgences',
    'share.title': 'Partager le Lien d\'Inscription',
    'share.message': 'Complétez votre inscription pour Casa Vista Hermosa',
    'share.copy': 'Copier le lien',
    'share.whatsapp': 'Partager via WhatsApp',
    'share.email': 'Partager par Email',
    'share.copied': 'Lien copié!',
    'confirmation.title': 'Inscription Terminée!',
    'confirmation.thankYou': 'Merci',
    'confirmation.dataSaved': 'Vos informations ont été enregistrées correctement',
    'confirmation.groupStatus': 'État du Groupe',
    'confirmation.of': 'de',
    'confirmation.responsible': 'Responsable',
    'confirmation.registered': 'Enregistré',
    'confirmation.pending': 'En attente',
    'confirmation.registerNext': 'Enregistrer l\'invité suivant',
    'confirmation.pendingPlural': 'en attente',
    'confirmation.pendingSingular': 'en attente',
    'confirmation.allRegistered': 'Tous les invités ont terminé leur inscription!',
    'confirmation.allGuestsComplete': 'Tous les invités enregistrés!',
    'confirmation.fullAccessUnlocked': 'Accès complet déverrouillé',
    'confirmation.goToDashboard': 'Aller à Mon Séjour',
    'confirmation.shareRegistration': 'Partager l\'Inscription',
    'confirmation.shareDescription': 'Envoyez ce lien aux autres invités pour qu\'ils terminent leur inscription',
    'confirmation.copyLink': 'Copier le lien d\'inscription',
    'confirmation.shareWhatsApp': 'Partager via WhatsApp',
    'confirmation.shareEmail': 'Envoyer par Email',
    'confirmation.showQR': 'Afficher le code QR',
    'confirmation.continueToApp': 'Continuer vers l\'app',
    'confirmation.limitedFeatures': 'Certaines fonctionnalités seront limitées jusqu\'à ce que tous les invités terminent leur inscription',
    'confirmation.progressSaved': 'Votre progression a été enregistrée correctement',
  },
  de: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': 'Willkommen! Ihr Aufenthalt beginnt hier ✨',
    'welcome.guestsRegistered': 'Registrierte Gäste',
    'welcome.completeRegistration': 'Meine Registrierung abschließen',
    'welcome.step': 'Schritt 1 von 3',
    'welcome.share': 'Link teilen',
    'welcome.viewAccommodation': 'Unterkunft ansehen',
    'welcome.dataProtected': '🔒 Ihre Daten sind geschützt und verschlüsselt',
    'welcome.compliance': 'Wir erfüllen die DSGVO und spanische Vorschriften',
    'welcome.timeEstimate': '📋 Schließen Sie Ihre Registrierung in nur 3 Minuten ab',
    'welcome.contact': 'Kontakt',
    'dashboard.myStay': 'Mein Aufenthalt',
    'dashboard.myReservation': 'Meine Reservierung',
    'dashboard.openAccommodation': '🔓 Unterkunft öffnen',
    'dashboard.preferences': 'Aufenthaltspräferenzen',
    'dashboard.yourHost': 'Ihr Gastgeber',
    'dashboard.accommodationInfo': 'Unterkunftsinformationen',
    'dashboard.welcomeVideo': 'Willkommensvideo',
    'dashboard.localGuide': 'Lokaler Führer',
    'dashboard.customerSupport': 'Kundenservice',
    'dashboard.completeToUnlock': 'Schließen Sie Ihre Registrierung ab zum Entsperren',
    'dashboard.sendMessage': '💬 Nachricht senden',
    'dashboard.callNow': '📞 Jetzt anrufen',
    'dashboard.sendEmail': '📧 E-Mail senden',
    'dashboard.missingGuests': 'Fehlende Gäste zu registrieren',
    'dashboard.someFeaturesLimited': 'Einige Funktionen sind eingeschränkt, bis sich alle Gäste registrieren',
    'dashboard.reportIncident': 'Vorfall melden',
    'dashboard.reportIncidentTitle': 'Einen Vorfall Melden',
    'dashboard.incidentDescription': 'Beschreiben Sie das Problem',
    'dashboard.incidentSubmit': 'Bericht senden',
    'dashboard.incidentCancel': 'Abbrechen',
    'dashboard.openDoor': 'Haupttür Öffnen',
    'dashboard.openGarage': 'Garage Öffnen',
    'dashboard.unlockHistory': 'Öffnungsverlauf',
    'dashboard.unlockSuccess': 'Tür erfolgreich geöffnet',
    'dashboard.unlockFailed': 'Fehler beim Öffnen der Tür',
    'localGuide.restaurants': '🍽️ Restaurants',
    'localGuide.cafes': '☕ Cafés',
    'localGuide.supermarkets': '🛒 Supermärkte',
    'localGuide.transport': '🚇 Öffentliche Verkehrsmittel',
    'localGuide.tourist': '🏛️ Touristische Attraktionen',
    'localGuide.emergency': '🏥 Notdienste',
    'localGuide.entertainment': '🎭 Unterhaltung',
    'contact.title': 'Gastgeber kontaktieren',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Verfügbar 24/7 für Notfälle',
    'share.title': 'Registrierungslink teilen',
    'share.message': 'Schließen Sie Ihre Registrierung für Casa Vista Hermosa ab',
    'share.copy': 'Link kopieren',
    'share.whatsapp': 'Über WhatsApp teilen',
    'share.email': 'Per E-Mail teilen',
    'share.copied': 'Link kopiert!',
    'confirmation.title': 'Registrierung Abgeschlossen!',
    'confirmation.thankYou': 'Danke',
    'confirmation.dataSaved': 'Ihre Informationen wurden korrekt gespeichert',
    'confirmation.groupStatus': 'Gruppenstatus',
    'confirmation.of': 'von',
    'confirmation.responsible': 'Verantwortlich',
    'confirmation.registered': 'Registriert',
    'confirmation.pending': 'Ausstehend',
    'confirmation.registerNext': 'Nächsten Gast registrieren',
    'confirmation.pendingPlural': 'ausstehend',
    'confirmation.pendingSingular': 'ausstehend',
    'confirmation.allRegistered': 'Alle Gäste haben ihre Registrierung abgeschlossen!',
    'confirmation.allGuestsComplete': 'Alle Gäste registriert!',
    'confirmation.fullAccessUnlocked': 'Voller Zugriff freigeschaltet',
    'confirmation.goToDashboard': 'Zu Mein Aufenthalt',
    'confirmation.shareRegistration': 'Registrierung teilen',
    'confirmation.shareDescription': 'Senden Sie diesen Link an andere Gäste, damit sie ihre Registrierung abschließen können',
    'confirmation.copyLink': 'Registrierungslink kopieren',
    'confirmation.shareWhatsApp': 'Über WhatsApp teilen',
    'confirmation.shareEmail': 'Per E-Mail senden',
    'confirmation.showQR': 'QR-Code anzeigen',
    'confirmation.continueToApp': 'Zur App fortfahren',
    'confirmation.limitedFeatures': 'Einige Funktionen sind eingeschränkt, bis alle Gäste ihre Registrierung abschließen',
    'confirmation.progressSaved': 'Ihr Fortschritt wurde korrekt gespeichert',
  },
  nl: {
    'welcome.title': 'Casa Vista Hermosa',
    'welcome.subtitle': 'Welkom! Uw verblijf begint hier ✨',
    'welcome.guestsRegistered': 'Geregistreerde gasten',
    'welcome.completeRegistration': 'Mijn registratie voltooien',
    'welcome.step': 'Stap 1 van 3',
    'welcome.share': 'Link delen',
    'welcome.viewAccommodation': 'Accommodatie bekijken',
    'welcome.dataProtected': '🔒 Uw gegevens zijn beschermd en versleuteld',
    'welcome.compliance': 'We voldoen aan de AVG en Spaanse regelgeving',
    'welcome.timeEstimate': '📋 Voltooi uw registratie in slechts 3 minuten',
    'welcome.contact': 'Contact',
    'dashboard.myStay': 'Mijn Verblijf',
    'dashboard.myReservation': 'Mijn Reservering',
    'dashboard.openAccommodation': '🔓 Accommodatie openen',
    'dashboard.preferences': 'Verblijfsvoorkeuren',
    'dashboard.yourHost': 'Uw Gastheer',
    'dashboard.accommodationInfo': 'Accommodatie Informatie',
    'dashboard.welcomeVideo': 'Welkomstvideo',
    'dashboard.localGuide': 'Lokale Gids',
    'dashboard.customerSupport': 'Klantenservice',
    'dashboard.completeToUnlock': 'Voltooi uw registratie om te ontgrendelen',
    'dashboard.sendMessage': '💬 Bericht versturen',
    'dashboard.callNow': '📞 Nu bellen',
    'dashboard.sendEmail': '📧 E-mail versturen',
    'dashboard.missingGuests': 'Ontbrekende gasten om te registreren',
    'dashboard.someFeaturesLimited': 'Sommige functies zijn beperkt totdat alle gasten zich registreren',
    'dashboard.reportIncident': 'Incident melden',
    'dashboard.reportIncidentTitle': 'Een Incident Melden',
    'dashboard.incidentDescription': 'Beschrijf het probleem',
    'dashboard.incidentSubmit': 'Rapport versturen',
    'dashboard.incidentCancel': 'Annuleren',
    'dashboard.openDoor': 'Hoofddeur Openen',
    'dashboard.openGarage': 'Garage Openen',
    'dashboard.unlockHistory': 'Openingsgeschiedenis',
    'dashboard.unlockSuccess': 'Deur succesvol geopend',
    'dashboard.unlockFailed': 'Fout bij het openen van de deur',
    'localGuide.restaurants': '🍽️ Restaurants',
    'localGuide.cafes': '☕ Cafés',
    'localGuide.supermarkets': '🛒 Supermarkten',
    'localGuide.transport': '🚇 Openbaar vervoer',
    'localGuide.tourist': '🏛️ Toeristische attracties',
    'localGuide.emergency': '🏥 Nooddiensten',
    'localGuide.entertainment': '🎭 Entertainment',
    'contact.title': 'Gastheer contacteren',
    'contact.name': 'María García',
    'contact.phone': '+34 612 345 678',
    'contact.email': 'maria@casavistahermosa.com',
    'contact.available': 'Beschikbaar 24/7 voor noodgevallen',
    'share.title': 'Registratielink delen',
    'share.message': 'Voltooi uw registratie voor Casa Vista Hermosa',
    'share.copy': 'Link kopiëren',
    'share.whatsapp': 'Delen via WhatsApp',
    'share.email': 'Delen via e-mail',
    'share.copied': 'Link gekopieerd!',
    'confirmation.title': 'Registratie Voltooid!',
    'confirmation.thankYou': 'Bedankt',
    'confirmation.dataSaved': 'Uw informatie is correct opgeslagen',
    'confirmation.groupStatus': 'Groepsstatus',
    'confirmation.of': 'van',
    'confirmation.responsible': 'Verantwoordelijk',
    'confirmation.registered': 'Geregistreerd',
    'confirmation.pending': 'In behandeling',
    'confirmation.registerNext': 'Volgende gast registreren',
    'confirmation.pendingPlural': 'in behandeling',
    'confirmation.pendingSingular': 'in behandeling',
    'confirmation.allRegistered': 'Alle gasten hebben hun registratie voltooid!',
    'confirmation.allGuestsComplete': 'Alle gasten geregistreerd!',
    'confirmation.fullAccessUnlocked': 'Volledige toegang ontgrendeld',
    'confirmation.goToDashboard': 'Ga naar Mijn Verblijf',
    'confirmation.shareRegistration': 'Registratie Delen',
    'confirmation.shareDescription': 'Stuur deze link naar andere gasten zodat ze hun registratie kunnen voltooien',
    'confirmation.copyLink': 'Registratielink kopiëren',
    'confirmation.shareWhatsApp': 'Delen via WhatsApp',
    'confirmation.shareEmail': 'Versturen via e-mail',
    'confirmation.showQR': 'QR-code tonen',
    'confirmation.continueToApp': 'Doorgaan naar app',
    'confirmation.limitedFeatures': 'Sommige functies zijn beperkt totdat alle gasten hun registratie voltooien',
    'confirmation.progressSaved': 'Uw voortgang is correct opgeslagen',
  },
};

const languageNames: Record<Language, string> = {
  es: 'Español',
  en: 'English',
  ca: 'Català',
  fr: 'Français',
  de: 'Deutsch',
  nl: 'Nederlands',
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const getLanguageName = (lang: Language): string => {
    return languageNames[lang];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getLanguageName }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
